### ISSUE TITLE
[BUG] Mission Randomisation Has Chance of Rolling for Mission 6

### ISSUE THREAD

**Issue by tornado-ii** [Ngolinvaux/SA2Randomizer#1]
The "Mission 6" glitch is a glitch wherein the mission loaded belongs to the stage succeeding the one selection. This will load the stage you've selected normally, but will use the next stage (by ID)'s mission data (objective text etc). On most stages, this will make the stage unbeatable as touching the goal ring will softlock the game, the mission complete screen not appearing. In Kart Race stages, this can corrupt the save data of the next stage.
Randomising missions can cause a stage to load another stage's mission one (thus it is that stage's mission six) and cause a softlock that is unable to be escaped from without closing the game.

**Comment by Ngolinvaux** [comment]
Did you obtain this mod while running randomizer and no other mods? Randomized missions are restricted to a [1,5] range, and I've never run into this in my testing. Glad you bring it up.

**Comment by Ngolinvaux** [comment]
Will be fixed in coming patch. Good catch.
