### ISSUE TITLE
Pressing the Y button in any level ends it immediately.

### ISSUE THREAD

**Issue by withered-rose** [Ngolinvaux/SA2Randomizer#10]
**Describe the bug**
In any level or cutscene, pressing the Y button causes the level to end, sending the player to the results screen. I'm not sure if this is a glitch, but it's not mentioned in the changelog for the latest release. It does not occur in 4.2.3, but does occur in 4.2.4

**Comment by Ngolinvaux** [comment]
Oops! Developer testing feature I forgot to disable.

**Comment by Ngolinvaux** [comment]
hotfixed!
