### ISSUE TITLE
Impossible Chao Races?

### ISSUE THREAD

**Issue by RevoSucks** [Ngolinvaux/SA2Randomizer#12]
Are certain Chao Races supposed to be impossible? The maxed out egg lv 99 in everything can't beat Topaz 4 and Peridot 5 for example. Somehow these other chaos are *faster than a maxed out Chao.* What gives?

**Comment by Ngolinvaux** [comment]
Yeah, this is kind of a biproduct of a few things. The race Chao lvl 99 in everything has really good stats, but is limited in some senses. A power stat over 3600 would softlock on trees, too high of a fly stat would leave him oob forever etc. Enemy Chao on the other hand have a pretty set path they run on and don't over-fly the goal so they have impossible advantages at some races.

There's a couple solutions available right now, the simplest would be to disable random Chao race opponents in the config if you need to clear those races. You can also hatch a random egg with stats better than your lvl 99 Chao. Extremely unlikely but they're capped higher than the Rave egg Chao.

I'll work on rebalancing the scaling on the enemies and make sure they're all completable later in the week. For more updates join the discord! (link on the main page of this repo). 

Going to close this issue for now, but be assured I'll have some solution available the next patch I push out. Thank you and hope you enjoy the mod.
