### ISSUE TITLE
Glitch when using character and/or level rando

### ISSUE THREAD

**Issue by Scoobert555** [Ngolinvaux/SA2Randomizer#2]
> I have been trying to get one solid playthrough of this rando (no mission rando), but every time there is a level that has a glitched title card, with the text being the wrong size and the logo being 2 seemingly random sprites.
![20190407181116_1](https://user-images.githubusercontent.com/49377463/55690536-ef6ad800-5960-11e9-9878-ac252dc6ec7a.jpg)

**Comment by Scoobert555** [comment]
it seems to only occur when the game is trying to load a character besides the one you originally play as in that stage

**Comment by Ngolinvaux** [comment]
What settings do you have turned on? And have u any other mods currently or previously on?

**Comment by Scoobert555** [comment]
the only settings i have on are Randomize Character on Load and Remove Costumes, though this was occuring long before i activated those. Do i need to have all of the files included in the download put in the SA2Rando folder? I don't have all of them put in there. Also, no other mods

**Comment by Scoobert555** [comment]
Oh, wait, previously too? Yeah, i had a seperate item box rando activated at some point, but i think i wiped the last save file when i had it activated

**Comment by Ngolinvaux** [comment]
Everything in the SA2Rando.7z should be in your folder. Though, to be fair, I have no clue what's causing this. But including all the files is a good place to start.

**Comment by Ngolinvaux** [comment]
Let me check and see how item box randomizer works and if it would have any negative effects on rando

**Comment by Scoobert555** [comment]
here:
https://mm.reimuhakurei.net/sa2mods/ItemBoxRandomizer.7z

**Comment by Ngolinvaux** [comment]
Yeah I'm talking to Main Memory, to see if I can see the source code and maybe why that would happen if it's on his end. Honestly, if running rando with all the files included doesn't work. I'd try reinstalling sa2 or at least verifying the game files integrity via steam.

**Comment by Scoobert555** [comment]
i started a new save with all the files in place and things seem to be working fine so far. I'll get back to you if theres any issues

**Comment by Scoobert555** [comment]
while your here, is there any way to see what my current seed is?

**Comment by Ngolinvaux** [comment]
If you turn on level list log, it will include the seed at the top of the file
