### ISSUE TITLE
Soft-lock in Tails Crazy Gadget

### ISSUE THREAD

**Issue by Meteor371** [Ngolinvaux/SA2Randomizer#3]
The second mystic melody box (Next to the first tube section) is programmed to do the same thing as the first mystic melody box which creates platforms over the first acid pit. So tails just hits a wall and is unable to continue.

**Comment by Ngolinvaux** [comment]
This stage /character combination has been completed numerous times. I will talk to level design and see if he changed something that might have impacted the playability.

**Comment by Ngolinvaux** [comment]
It was brought to my attention that some graphics cards /settings have issues rendering mystic melody warps. That second statue should unlock a warp to the right of the tube.

**Comment by Ngolinvaux** [comment]
Can confirm the warp is there in current patch, so this is likely a graphical issue on your end. Lemme ask around for a solution

**Comment by Ngolinvaux** [comment]
https://steamcommunity.com/app/213610/discussions/0/1693785669848380532/

This thread seems to have a couple potential solutions for you.

**Comment by Meteor371** [comment]
OK, took me a bit to get a level with a portal to check it out. But that is indeed the problem. Thanks for clearing that up!
