### ISSUE TITLE
Mechless Eggman's Aquatic Mine Impossible Emerald

### ISSUE THREAD

**Issue by aaronlink127** [Ngolinvaux/SA2Randomizer#4]
In Mechless Eggman's Aquatic Mine, there's one emerald that can spawn whose first hint is "Three... no, one fan?" or something like that. It requires Mystic Melody, but mechless characters don't have Mystic Melody, so the emerald is unreachable.

**Comment by Ngolinvaux** [comment]
Have you tried using Mystic Melody anyway? Press B near a statue. See what happens.

**Comment by Ngolinvaux** [comment]
Also there is a link to the SA2 Rando's Discord on the main page of the repo. You can find tons of people to help, and likely faster responses too.
