### ISSUE TITLE
King Boom Boo is impossible without digging

### ISSUE THREAD

**Issue by aaronlink127** [Ngolinvaux/SA2Randomizer#5]
And, well, most characters can't dig.

**Comment by Ngolinvaux** [comment]
You don't need to dig to dig KBB up. You simply need an action with the same ID as dig. As it so happens that action characters can sommersalt on top of his to "dig" him up.

**Comment by Ngolinvaux** [comment]
This is being looked at though as we are noticing a ton of people never figuring that out, if we cannot make it more obvious we will either make it optional or remove it.
