### ISSUE TITLE
Metal Sonic crashing game

### ISSUE THREAD

**Issue by AccordionCoverist** [Ngolinvaux/SA2Randomizer#6]
So whenever I get to play as Metal Sonic, any time I press B while he is in the air, my game automatically crashes and closes out. 
As far as I know, it must be specifically this mod because I tried it with most of my other mods deactivated just to see.

**Comment by Ngolinvaux** [comment]
Do you have the code for "Shadow having bounce bracelet" turned on?

**Comment by AccordionCoverist** [comment]
I made sure I had it turned off when I tested it, just to make sure. Im about to try it with all other mods off so I'll update once tested

**Comment by AccordionCoverist** [comment]
Hmm. Well, it must've been the Have All Upgrades one that messed it up. My bad haha!!
