### ISSUE TITLE
Can't Get Sonic Adventure and Sonic Heroes Lines to Work

### ISSUE THREAD

**Issue by Grip555** [Ngolinvaux/SA2Randomizer#9]
- OS Windows 10 x64
 - Version 4.2.2

I followed the steps by creating a game with Japanese language on, exiting the game, then loading it with the randomizer on. I also put the audio file in the right place.

**Comment by Ngolinvaux** [comment]
Not shocking. It's been well established at this point that the feature isn't working very well. I have no other suggestions, I'd probably just remove the file and wait to see if we ever have a break through. These issues baffle every one of the sa2 modders, so I wouldn't expect anything soon.
